### ISSUE TITLE
Use non-blocking output for stdout

### ISSUE THREAD

**Issue by WyriHaximus** [clue/php-stdio-react#47]
Went through the source and came across https://github.com/clue/php-stdio-react/blob/0c9a7fe7a87643499c56dc5af63c3e497b717d79/src/Stdout.php#L11 noting STDOUT is used in a blocking manner. Is there anything special that needs to be done, or can be be wrapped into a `WritableResourceStream` and hooked into the loop easily?

**Comment by clue** [comment]
I suppose this is related to #6, but we'd have to look into this. Do you feel like filing a PR? :+1: 

For the reference: The `WritableResourceStream` didn't exist back when this repo has been created and part of the motivation for creating that class was actually for this repo :shipit:

**Comment by WyriHaximus** [comment]
> Do you feel like filing a PR?

Working on https://github.com/wyrihaximus/reactphp-psr-3-stdio so yeah I'm up for filing a PR :grinning: .

> For the reference: The WritableResourceStream didn't exist back when this repo has been created and part of the motivation for creating that class was actually for this repo :shipit:

I'm aware, found out that file it from 2014 no worries :+1:

**Comment by WyriHaximus** [comment]
Not that the two referenced PR's are in I've started working on this :tada:

**Comment by WyriHaximus** [comment]
Interesting enough my current local code closes `STDOUT` and cuts phpunit output :zipper_mouth_face:
